### ISSUE TITLE
Result Board  Order

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/stones-spec#25]
Hi!
When a program doesn't do what's expected, 3 boards are shown with very small titles. I have to think a bit to see which is which.
I'd rather have some arrow between the initial and final boards.

When result OK:
Initial Board [Arrow ->] Final Board
When result Wrong:
Initial Board [Arrow ->] Wrong Final Board (with a red X at the side, I think?)
(and below)
Initial Board [Arrow ->] Expected Final Board

I don't know, I'd test a bit around to see How does the arrow fit in the initial/expected/wrong boards context

**Comment by faloi** [comment]
Related to #19

**Comment by faloi** [comment]
Moved to https://github.com/mumuki/mumuki-gobstones-server/issues/80
