### ISSUE TITLE
Structured output

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/stones-spec#26]
We need to switch to structured output format, in the same way Haskell and Ruby runners do. 

This allows better output and less rendering logic within the runner.

**Comment by flbulgarelli** [comment]
This means we have already structured the gobstones server? Or we have to create another issue for that?

**Comment by micaelafmartino** [comment]
Oh now I see why you asked that :P

It's already done here mumuki/mumuki-gobstones-server#68
