### ISSUE TITLE
Explicilty show which example has failed as part of the test output

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/stones-spec#5]
~~Currently, the runner only displays the initial, expected final and actual final boards. The user has tomanually compare expected and actual boards to discover which example has failed.~~

It would be nice to display a green tick/red cross in those cases to clearly indicate which examples have failed.

**Comment by faloi** [comment]
This is not true. 

Right now, the 3 boards (initial, actual, expected) are shown **only** when the test fails. However, I agree that adding a tick/cross would be useful.

**Comment by flbulgarelli** [comment]
Yes, you are right. 

The issue is that, on one hand it is a good is to always show both initial and final board. And on the other hand, to be more explicit about which test has failed. A cross/tick should be enought. We coud use `fontawesome` icons, since it is included in mumuki

**Comment by faloi** [comment]
mumuki/mumuki-platform#223 should be addressed first

**Comment by flbulgarelli** [comment]
Since we have already address it, we can go on with this now

**Comment by faloi** [comment]
+1 to this, we should address it now

**Comment by faloi** [comment]
The real issue here is that the gobstones runner doesn't support structured output yet. See https://github.com/mumuki/mumuki-gobstones-server/issues/65.
